### ISSUE TITLE
Update guzzle-client to v7

### ISSUE THREAD

**Issue by rizalfauzie** [xendit/xendit-php#107]
Hi @stanleynguyen i concern with your comment on https://github.com/xendit/xendit-php/issues/67#issuecomment-618150627

But why guzzle on composer.json strict to version 6?

I have other package that require `guzzlehttp/guzzle` version 7.
I can't install this package. Please Help. :pray:

**Comment by stanleynguyen** [comment]
Hi @rizalfauzie, we will consider upgrading our GuzzleClient to 7.
In the meantime, you can install guzzle 7 in your project and swap the http client with https://github.com/xendit/xendit-php#use-custom-http-client

**Comment by rizalfauzie** [comment]
i can't @stanleynguyen 

```bash
  Problem 1
    - xendit/xendit-php 2.5.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - xendit/xendit-php 2.5.1 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Installation request for guzzlehttp/guzzle ^7.2 -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - Installation request for xendit/xendit-php ^2.5 -> satisfiable by xendit/xendit-php[2.5.0, 2.5.1].
```

Why not just add version `^6.0|^7.0` on composer.json?
is there any backward compatibility within this package?

**Comment by stanleynguyen** [comment]
> i can't @stanleynguyen
> 
> ```shell
>   Problem 1
>     - xendit/xendit-php 2.5.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
>     - xendit/xendit-php 2.5.1 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
>     - Installation request for guzzlehttp/guzzle ^7.2 -> satisfiable by guzzlehttp/guzzle[7.2.0].
>     - Installation request for xendit/xendit-php ^2.5 -> satisfiable by xendit/xendit-php[2.5.0, 2.5.1].
> ```
> 
> Why not just add version `^6.0|^7.0` on composer.json?
> is there any backward compatibility within this package?

Oh interesting. I didn't know the composer dependency model is this strict. Lemme put in a quick fix

**Comment by stanleynguyen** [comment]
Hey @rizalfauzie please try again with https://packagist.org/packages/xendit/xendit-php#2.5.2
I'm repurposing this issue as a request to update guzzle-client

**Comment by rizalfauzie** [comment]
thank you, it work.
