### ISSUE TITLE
Class Xendit/Xendit not found

### ISSUE THREAD

**Issue by anggi117** [xendit/xendit-php#117]
Hai kak, saya ingin bertanya kenapa ya class xendit tidak ditemukan
Library yang saya gunakan versi 2.6

![image](https://user-images.githubusercontent.com/42998655/106245955-ecc92900-623f-11eb-96bc-75d3128999ee.png)

**Comment by franschaniago** [comment]
saya juga mengalamai kendala yang sama di xendit versi 1.4 dengan php 7.1

**Comment by edwinyoyada** [comment]
halo, bisa kasi code snippetnya?

**Comment by edwinyoyada** [comment]
> saya juga mengalamai kendala yang sama di xendit versi 1.4 dengan php 7.1

@franschaniago mohon gunakan versi 2

**Comment by edwinyoyada** [comment]
halo @anggi117 apakah masih menghadapi issue yang sama?

**Comment by stanleynguyen** [comment]
Stale. Closing
