### ISSUE TITLE
Ewallet versi terbaru  "Failed to validate the request, 1 error occurred. " error 400

### ISSUE THREAD

**Issue by mfauzann** [xendit/xendit-php#122]
Halo Semuanya saya ada kendala dalam implementasi pembayaran ewallet versi baru. saya sudah mengikuti semua aturan yang ditentukan oleh pihak xendit, saya udah mencoba beberapa cara, bahkan sama sampai buka doc. postman xendit untuk test secara langsung dengan menggunakan secret key milik saya. dan hasilnya tetap sama. seperti dibawah ini

![image](https://user-images.githubusercontent.com/16873620/109823162-43c08480-7c6a-11eb-9eb4-6de2a6c0c997.png)

ini code yang saya gunakan..
![image](https://user-images.githubusercontent.com/16873620/109823471-8aae7a00-7c6a-11eb-9d2e-a027082226d2.png)

![image](https://user-images.githubusercontent.com/16873620/109823540-9bf78680-7c6a-11eb-96fd-2dc7c5627467.png)

ini param yang saya set
if($request->ewallet_type == 'SHOPEEPAY'){
                        $payload = [
                            'reference_id' => $vendors->vendor->prefix.'-'.$request->external_id,
                            'currency'=>'IDR',
                            'checkout_method'=>'ONE_TIME_PAYMENT',
                            'amount' => (int)$request->amount,
                            'channel_code' => 'ID_'.$request->ewallet_type,
                            'channel_properties'=>[
                                    'success_redirect_url'=>$request->success_redirect_url
                            ]  
                        ];
                    }

**Comment by luminto17** [comment]
selamat malam @mfauzann , untuk request payload di Postman apakah boleh di paste disini agar kami bantu proses pengecekan?

**Comment by mfauzann** [comment]
@luminto17 itu mas, saya test langsung hit API https://api.xendit.co/ewallets/charges 
di header ditambahkan "callback-url"

{
    "reference_id": "order-test-id-123",
    "currency": "IDR",
    "amount": 20101,
    "checkout_method": "ONE_TIME_PAYMENT",
    "channel_code": "ID_OVO",
    "channel_properties": {
        "mobile_number": "+6287821027361"
        },
}

**Comment by mfauzann** [comment]
{
"reference_id": "order-test-id-123",
"currency": "IDR",
"amount": 20101,
"checkout_method": "ONE_TIME_PAYMENT",
"channel_code": "ID_OVO",
"channel_properties": {
"mobile_number": "+6287821027361"
}
}

**Comment by luminto17** [comment]
Baik mas @mfauzann . Saya coba di Postman saya dengan payload yang sama namun tetap berhasil. Apakah boleh di paste disini callback URL yang diset untuk kami bantu pengecekan?
<img width="980" alt="Screen Shot 2021-03-03 at 22 06 41" src="https://user-images.githubusercontent.com/9628847/109825805-c0ecf900-7c6c-11eb-90cc-92ba1006f69b.png">

**Comment by luminto17** [comment]
selamat malam mas @mfauzann , kendala yang kami temukan ada pada format callback URLnya. Request payload nya `http://localhost:8181/callbacks/ewallets/paid` mohon dikoreksi apabila salah. 

Saat ini, callback URL kami tidak dapat mendukung format localhost ya. Mungkin mas Fauzan bisa mencoba callback URL dengan menggunakan https://webhook.site/ atau https://ngrok.com/ untuk mocking callback URL

Mohon kabari lebih lanjut ya mas apabila masih terjadi kendala

**Comment by mfauzann** [comment]
@luminto17 malam maaf tadi saya ada keperluan dulu, oh bgtu ya, kmren-kmren sempat bisa pake local, makannya saya agak kebingungan, oh ya saya blm dapat akun xendit nya karena yang memegang dashboard nya team lead saya. 
Nanti saya kabari kembali jika ada kendala. terimakasih juga untuk rekomendasi callback URL mas.
terimakasih..

**Comment by luminto17** [comment]
baik mas @mfauzann sama2. selamat malam dan selamat beristirahat

**Comment by iniakunhuda** [comment]
Hi mas @luminto17, I've got same error 
"Failed to validate the request, 1 error occurred. at xxx/xendit/xendit-php/src/HttpClient/GuzzleClient.php:167)"

How can I solve this issue? any suggestion?

**Comment by HendryZheng** [comment]
Hi @iniakunhuda could you please share us which method / API you are trying to call and also your parameters to the API call?

**Comment by iniakunhuda** [comment]
> Hi @iniakunhuda could you please share us which method / API you are trying to call and also your parameters to the API call? This could help us understand better and finding out the problem to your situation.

Hi thanks for reply, I used this method and params to pay with OVO payment

```php
\Xendit\EWallets::createEWalletCharge($paymentParams);
```

with params

```json
{"params":{"reference_id":"AM00065-210920-0047-1632110345","currency":"IDR","amount":40000,"checkout_method":"ONE_TIME_PAYMENT","channel_code":"ID_OVO","channel_properties":{"mobile_number":"085856190xx","success_redirect_url":"https://site-test.aratamart.id/order/success/xxx"}}}
```

**Comment by xen-HendryZheng** [comment]
HI @iniakunhuda Request yang anda kirim ke dalam method API createEWalletCharge spertinya tidak sesuai.
Bisa di hapus referensi "params" nya, dan hanya masukkan attribute dari object key dan value dari array nya saja?
Seperti ini (json):
```
{
    "reference_id": "AM00065-210920-0047-1632110345",
    "currency": "IDR",
    "amount": 40000,
    "checkout_method": "ONE_TIME_PAYMENT",
    "channel_code": "ID_OVO",
    "channel_properties": {
      "mobile_number": "085856190xx",
      "success_redirect_url": "https://site-test.aratamart.id/order/success/xxx"
}
```

Seperti ini (PHP):
```
$ewalletChargeParams = [
    "reference_id" => "AM00065-210920-0047-1632110345",
    "currency" => "IDR",
    "amount" => 40000,
    "checkout_method" => "ONE_TIME_PAYMENT",
    "channel_code" => "ID_OVO",
    "channel_properties" => [
      "mobile_number"=> "085856190xx",
      "success_redirect_url" => "https://site-test.aratamart.id/order/success/xxx"
    ]
];
```

Untuk referensi pemakaian SDK bisa refer ke sini juga ya: [https://github.com/xendit/xendit-php#create-e-wallet-charge](url)
dan API referensi : [https://developers.xendit.co/api-reference/#create-ewallet-charge](url)

Mohon di info lebih lanjut ya apabila masih terjadi kendala

**Comment by iniakunhuda** [comment]
Hi! Sorry issue was solved, my mistake write phone_number without country prefix with +62. Thank you everyone

**Comment by xen-HendryZheng** [comment]
Glad to hear that @iniakunhuda ! Let us know if you face any other difficulties integrating with Xendit through this SDK !

**Comment by ekibagascan** [comment]
Halo saya juga punya problem yang sama
{
  status: 400,
  code: 'API_VALIDATION_ERROR',
  message: 'Invalid channel_properties for ID_OVO. Expecting mobile_number to be provided'
}
padahal payloadnya sudah complete tapi mau POST tidak bisa, saya coba di Postman juga sama. Minta tolong bantuannya

**Comment by xen-HendryZheng** [comment]
Halo @ekibagascan mungkin bisa di lampirkan payload request nya?

**Comment by ekibagascan** [comment]
Ini payloadnya, maaf baru balas
{
"reference_id":"617cdf9da8ef3400044adf69",
"currency": "IDR",
"amount": 8888,
"checkout_method": "ONE_TIME_PAYMENT",
"channel_code": "ID_OVO",
"channel_properties": {
    "mobile_number":"+6288803890773",
    "success_redirect_url":"https://dashboard.xendit.co/register/1"
  }
}

**Comment by ekibagascan** [comment]
Ini kode backend saya gan
![Xendit Controller](https://user-images.githubusercontent.com/41675517/140590241-0babe308-17bf-4927-a6e9-b6b5d45c05f1.png)

**Comment by ekibagascan** [comment]
Ini Postmannya, jadi saya pake Ngrok untuk servernya/
![postman](https://user-images.githubusercontent.com/41675517/140591044-5043bce4-dca9-48d3-96ab-c4b99c8cf4c7.png)

**Comment by ekibagascan** [comment]
Setelah saya tambahkan process.env.Xendit_URL di code backendnya, responnya jadi begini gan:
{
  status: 404,
  code: 'NOT_FOUND',
  message: "endpoint doesn't exist. Got error: Path was not found when validating"
}

**Comment by ekibagascan** [comment]
### **UPDATE!** 
Saya coba tambahkan mobile_number di luar channel_properties sudah bisa tetapi diblock sama CORS, padahal sudah saya tambahkan headers di code backend saya dan saya sudah pakai Ngrok. Gimana ya ini solusinya?

![postman1](https://user-images.githubusercontent.com/41675517/140592461-86cb56ff-b8f0-4971-aa2a-3c81c0ad741f.png)

**Comment by ekibagascan** [comment]
### **Update**
Sudah bisa create charge tapi setelah itu muncul error di server gan:
created ewallet payment charge: {
  id: 'ewc_f69fcaa9-ebd1-4959-bcf1-233986034459',
  business_id: '613e0d35e95e904011c15ea9',
  reference_id: '617cdf9da8ef3400044bdf49',
  status: 'PENDING',
  currency: 'IDR',
  charge_amount: 7886,
  capture_amount: 7886,
  refunded_amount: null,
  checkout_method: 'ONE_TIME_PAYMENT',
  channel_code: 'ID_OVO',
  channel_properties: { mobile_number: '+6288803890773' },
  actions: null,
  is_redirect_required: false,
  callback_url: 'https://0971-115-178-226-93.ngrok.io/api/transactions/ewallets/charges',
  created: '2021-11-06T02:10:13.379Z',
  updated: '2021-11-06T02:10:13.379Z',
  void_status: null,
  voided_at: null,
  capture_now: true,
  customer_id: null,
  payment_method_id: null,
  failure_code: null,
  basket: null,
  metadata: null
}
**Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (C:\Users\Eki Bagas\Desktop\btopupgamesku\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\Eki Bagas\Desktop\btopupgamesku\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\Eki Bagas\Desktop\btopupgamesku\node_modules\express\lib\response.js:267:15)
    at EwalletCharge (file:///C:/Users/Eki%20Bagas/Desktop/btopupgamesku/controllers/ewallets.js:48:21)    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
{
  status: 400,
  code: 'API_VALIDATION_ERROR',
  message: 'Failed to validate the request, 4 errors occurred.'
}**

Apa karena callbacknya ya?

**Comment by ekibagascan** [comment]
Ini gan
{
amount: 122000
category: "Mobile Legends"
channel_code: "ID_OVO"
channel_properties: {mobile_number: "+6288803890773",…}
failure_redicect_url: "http://localhost:3000/etalase/Mobile Legends/failure/6187ad297dae093f80ac456e"
mobile_number: "+6288803890773"
success_redirect_url: "http://localhost:3000/etalase/Mobile Legends/status/6187ad297dae093f80ac456e"
checkout_method: "ONE_TIME_PAYMENT"
currency: "IDR"
mobile_number: "+6288803890773"
reference_id: "6187ad297dae093f80ac456e"
}

**Comment by ekibagascan** [comment]
Sekarang errornya gini gan @xen-HendryZheng 
{
  status: 400,
  code: 'API_VALIDATION_ERROR',
  message: 'Failed to validate the request, 1 error occurred.'
}

Saya coba di Postman bisa tapi di localhost atau domain asli ga bisa gan, di Postman saya pakai ini:
https://d31c-114-79-16-30.ngrok.io/api/transactions/ewallets/charges
