### ISSUE TITLE
Callback with parameter

### ISSUE THREAD

**Issue by henzan02** [xendit/xendit-php#125]
Halo, apakah ada sample untuk callback yang mengambil data dari database atau dari nomor invoice xendit?

`function createCallbackVirtualAccount ($external_id, $bank_code, $name, $virtual_account_number = null) {
            $curl = curl_init();

            $headers = array();
            $headers[] = 'Content-Type: application/json';

            $end_point = $this->server_domain.'/callback_virtual_accounts';

            $data['external_id'] = $external_id;
            $data['bank_code'] = $bank_code;
            $data['name'] = $name;

            if (!empty($virtual_account_number)) {
                $data['virtual_account_number'] = $virtual_account_number;
            }

            $payload = json_encode($data);

            curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
            curl_setopt($curl, CURLOPT_USERPWD, $this->secret_api_key.":");
            curl_setopt($curl, CURLOPT_URL, $end_point);
            curl_setopt($curl, CURLOPT_POST, true);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $payload);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

            $response = curl_exec($curl);
            curl_close($curl);

            $responseObject = json_decode($response, true);
            return $responseObject;
        }`

Apakah ini masih bisa digunakan?

**Comment by luminto17** [comment]
Selamat siang @henzan02 , kami ada API untuk mengambil data VA ya dengan menggunakan function ini https://github.com/xendit/xendit-php#get-fixed-virtual-account

Apakah bisa diinformasikan lebih lanjut mas @henzan02 sedang berada di tahap apa untuk kami bantu lebih lanjut?
- Pembuatan VA
- Ambil data VA
- Menerima callback dari Xendit ketika VA sudah aktif

**Comment by henzan02** [comment]
@luminto17 
Saya tidak menggunakan fixed VA. 
Flow saya : 
1. User Create Invoice dari checkout
2. Redirect ke xendit invoice (user bisa memilih pembayaran VA/CC)
3. Admin mendapatkan notifikasi dan database pesanan terupdate. 

yang saya butuhkan bagaimana script agar admin dan database saya bisa terupdate.

Saya kemarin lihat dari dokumentasi disini : 
https://docs.xendit.co/id/xeninvoice/notifikasi-dan-callback

Dimana saya harus meletakkan script itu? setelah user checkout atau dimana ya?

Thanks

**Comment by luminto17** [comment]
selamat siang pak @henzan02 

benar untuk invoice bapak dapat menggunakan fitur callback yang kami sediakan untuk notifikasi pembayaran maupun invoice telah expired ya

yang bapak butuhkan adalah
1. setup 1 URL untuk menerima notifikasi yang akan kami kirim dalam bentuk JSON
2. Daftarkan URL tersebut ke bagian Invoice callback disini https://dashboard.xendit.co/settings/developers#callbacks. Pendaftaran URL dapat dilakukan pada Test mode maupun Live mode
3. Testing dan pastikan data sudah berhasil diterima dengan baik ke sistem bapak
4. Simpan data yang diterima melalui callback ke dalam database bapak dan update admin page bapak berdasarkan data yang telah disimpan
5. Kami juga mengirimkan token untuk bapak melalukan validasi bahwa memang benar callback yang dikirimkan adalah dari Xendit. bisa di cek di callback nya ada parameter `x-callback-token` ya. Value nya bisa di validasi sesuai dengan apa yang ditampilkan di dashboard. Selengkapnya bisa diikuti disini ya pak https://docs.xendit.co/api-integration/callback/setup

**Comment by adityarx** [comment]
Closing as this is inactive
