### ISSUE TITLE
How to get Token ID for credit card charge? 

### ISSUE THREAD

**Issue by muh-hizbe** [xendit/xendit-php#134]
Where i can get token_id value for credit card charge?

**Comment by stanleynguyen** [comment]
Hey @muh-hizbe , you will need to use xendit.js in your frontend to generate this token. Check [this doc](https://docs.xendit.co/credit-cards/integrations/tokenization#collecting-card-details-using-xenditjs) out

**Comment by muh-hizbe** [comment]
hey @stanleynguyen , there's any library to installation in NextJS ? I was open [this doc](https://docs.xendit.co/credit-cards/integrations/tokenization#collecting-card-details-using-xenditjs), but I only saw cdn of xendit.js

**Comment by stanleynguyen** [comment]
@muh-hizbe yes u can use [this package](https://www.npmjs.com/package/xendit-js-node)
