### ISSUE TITLE
Update invoice payer_email and description as optional

### ISSUE THREAD

**Issue by wwchen21227** [xendit/xendit-php#135]
https://github.com/xendit/xendit-php/blob/e4df989aac9e71512a544e7cb69f863d51adcfe3/src/Invoice.php#L49

**Comment by iprastha** [comment]
This resulted in inconsistencies between the documentation ( https://developers.xendit.co/api-reference/?php#create-invoice ) and the actual result, without parsing payer_email and description (marked as optional in the docs), invoice won't be created

**Comment by derryberni** [comment]
I also experienced the same thing, need fix it

**Comment by David-Kurniawan** [comment]
#147

**Comment by adityarx** [comment]
Closing as resolved~
