### ISSUE TITLE
PROCESSOR_ERROR ketika menggunakan metode pembayaran Credit card mode DEV untuk testing

### ISSUE THREAD

**Issue by mfauzann** [xendit/xendit-php#137]
halo semua nya ada pernah mengalami 
PROCESSOR_ERROR ketika menggunakan metode pembayaran Credit card mode DEV untuk testing

result seperti dibawah ini:

"PROCESSOR_ERROR"

{
"id": "610275304c25f40020d9bd43", "eci": "07", "status": "FAILED", "created": "2021-07-29T09:30:24.415Z", "currency": "IDR", "cvn_code": "3", "card_type": "CREDIT", "card_brand": "VISA", "descriptor": "XENDIT*HALOSIS", "business_id": "5bc53beed295f32a1e169b51", "charge_type": "SINGLE_USE_TOKEN", "external_id": "XX22-ASDF-HEHKAMU-2021-00025", "merchant_id": "xendit_ctv_agg", "capture_amount": "11000", "failure_reason": "PROCESSOR_ERROR", "authorization_id": "6102752e4c25f40020d9bd42", "authorized_amount": "11000", "issuing_bank_name": "PT. Bank Rakyat Indonesia (Persero)", "masked_card_number": "400000XXXXXX0002", "credit_card_token_id": "6102752c450d580020488a9c", "merchant_reference_code": "6102752c852e017b7f4571bb"
}

problemnya kenapa? beberapa hari yang lalu masih bisa digunakan.

**Comment by stanleynguyen** [comment]
Hey @mfauzann, the error happened because you're using a test card in live environment.

**Comment by mfauzann** [comment]
Ohh ..  ahh, Thank u . 😅
