### ISSUE TITLE
How go generate token on credit cart

### ISSUE THREAD

**Issue by ferdinand-tjandra** [xendit/xendit-php#157]
Hi all,

sorry if im missing to read the documentation. i still confuse how do we generate the token ID when we want to use credit cart option payment?

please help

**Comment by xen-HendryZheng** [comment]
Hi @ferdinand-tjandra 
For the Token ID, it is part of tokenization process which you can find more details here: [https://docs.xendit.co/credit-cards/integrations/tokenization](https://docs.xendit.co/credit-cards/integrations/tokenization)

**Comment by shafarizkyf** [comment]
same question, I couldn't find it also on the postman example. That link refers to xendit.js, may I know the endpoint to create token API? I want to generate token using curl if this part does not exist yet in this library

**Comment by shafarizkyf** [comment]
I also tried using the [example form](https://js.xendit.co/test_tokenize.html?_ga=2.223546587.1787959888.1637403526-1826654938.1635564775&_gac=1.18373067.1636378865.Cj0KCQiAsqOMBhDFARIsAFBTN3cD_9wkJhuMxJ_H5ICgYlMDgS1Yv5ryhUX91aKIMug6zDi3SC7h3QEaAt__EALw_wcB) but none of the provided keys (both mine or the example given) is work

**Comment by shafarizkyf** [comment]
In case anyone needs it, just got it working, here's mine on Laravel
![image](https://user-images.githubusercontent.com/20674388/142724445-bef1762b-1888-479a-ba91-65aeaa2ad08b.png)
