### ISSUE TITLE
Error saat run file dari php client library xendit

### ISSUE THREAD

**Issue by ujang19** [xendit/xendit-php#159]
Saya mau mencoba run file php dari xendit client library, tapi error di api operation request

PS C:\xampp\htdocs\QR> php .\vendor\xendit\xendit-php\examples\BalanceExample.php
PHP Notice:  Undefined variable: params in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\examples\BalanceExample.php on line 21

Notice: Undefined variable: params in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\examples\BalanceExample.php on line 21
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 68

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 68
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 72

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 72
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 76

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 76
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 80

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 80
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 84

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 84
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 89

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\ApiOperations\Request.php on line 89
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\HttpClient\GuzzleClient.php on line 115

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\QR\vendor\xendit\xendit-php\src\HttpClient\GuzzleClient.php on line 115
array(1) {
  ["balance"]=>
  int(1094)
}

**Comment by xen-HendryZheng** [comment]
Halo @ujang19 Boleh di infokan apakah sudah include dari composer utk php-sdk nya sendiri? Dan juga untuk examples, mostly hanya contoh ya, bisa di modifikasi parameter sesuai kebutuhan dan jangan lupa utk refer ke dokumentasi kita juga ya. Terima kasih.
