### ISSUE TITLE
How can i set Header Parameter?

### ISSUE THREAD

**Issue by munir1121** [xendit/xendit-php#162]
There is no option for Header Parameter.

**Comment by munir1121** [comment]
https://paste.pics/880d891a72dcc9d26ee2fb6ae820053d

I would like to set this header to request.

**Comment by xen-HendryZheng** [comment]
Hi @munir1121 Please refer to this guide : https://github.com/xendit/xendit-php#create-invoice

**Comment by luminto17** [comment]
Hi @munir1121 , we recommend to use the latest version https://github.com/xendit/xendit-php/releases/tag/2.17.0, so you can enjoy the benefit of setting header in request for Create, Update, and Get APIs

**Comment by luminto17** [comment]
stale PR.
