### ISSUE TITLE
Class Xendit/Xendit not found

### ISSUE THREAD

**Issue by rdecastro31** [xendit/xendit-php#165]
Hi,

I installed the xendit-php library version 1.4  on our local machine with php version 7.1.

Upon testing, an error appeared saying "Class Xendit/Xendit" not found, I even changed the "/" to "\" but still error occurs.

Any help would be appreciated. Thanks and God bless!

**Comment by luminto17** [comment]
Hi @rdecastro31 , well noted on the issue.

May we know what Xendit products are you planning to use? We recommend to install the latest version of our Xendit PHP, which is v.2.17.0 to get all the latest benefits https://github.com/xendit/xendit-php/releases/tag/2.17.0 (and hopefully solve this issue)

Looking forward hearing from you. Thank you

**Comment by rdecastro31** [comment]
Hi Xendit Team,

We are currently using php version 7.1, is this compatible with the latest version?

Thanks for the prompt response.

Raphael De Castro
+63917-823-9348
Senior Web and Mobile Developer
________________________________

**Comment by luminto17** [comment]
Hi @rdecastro31 , unfortunately the latest version of our PHP SDK requires PHP version >=7.2.0 https://packagist.org/packages/xendit/xendit-php#2.17.0

We are no longer developing any products on Xendit PHP version 1 as written here https://developers.xendit.co/api-reference/#php, so there might a chance some Xendit products you are looking to integrate might not available in Xendit PHP v1.  Could we check with you what Xendit products are you using?

We will try to check and reproduce the issue 1.4 and will share update when we have one

**Comment by rdecastro31** [comment]
Hi Guys,

I'll just upgrade our PHP version >= 7.2 and will update the xendit-php library.

Will let you know for any progress 

Thanks for the clarifications

**Comment by xen-HendryZheng** [comment]
HI @rdecastro31 Is everything alright with your integration with xendit-php library? Please let us know if you need further assistance.
