### ISSUE TITLE
Expire Invoice with param for-user-id

### ISSUE THREAD

**Issue by ipoool** [xendit/xendit-php#166]
Currently, function expireInvoice() only have 1 parameter "$id". is it possible to add new param to support expire invoice based on sub-account? seems, I think you guys just add parameters like the below:

```
public static function expireInvoice($id, $params = [])
    {
        $url =  '/invoices/' . $id . '/expire!';

        return static::_request('POST', $url, $params);
 }
```

**Comment by xen-HendryZheng** [comment]
Hi @ipoool Please run composer update. We've added at 2.7.1 here : https://github.com/xendit/xendit-php/releases/tag/2.17.1

Thank you !
