### ISSUE TITLE
Get Available Banks

### ISSUE THREAD

**Issue by halohaikamu** [xendit/xendit-php#168]
<?php

namespace App\Controllers;

class Bank extends BaseController
{
    public function index()
    {
        $options['secret_api_key'] = 'xnd_development_nedL5epdDZnTyqT1u9voYt2aH2ze0cWUvBgXx71ixwGBAJ1GTPT9hfT0vzhIg8';

        $xenditPHPClient = new XenditClient\XenditPHPClient($options);

        $response = $xenditPHPClient->getAvailableDisbursementBanks();
        print_r($response);
    }
}

**Comment by luminto17** [comment]
Hi @halohaikamu , anything we can help? Do you mind to share more context of your problem or ask, if any?
Thank you

**Comment by adityarx** [comment]
Closing this issue as no longer active
