### ISSUE TITLE
Can not pass decimal number to Xendit 

### ISSUE THREAD

**Issue by tannguyen-iprice** [xendit/xendit-php#171]
Currently, the total payment is being rounded in Xendit gateway. 

E.g: in the checkout page, total payment is 23,545.**50** but the total payment in Xendit gateway is 23,545.**00**

Here is our EVN info
**Version**: 1.4
**OS**: Ubuntu

I think it's happening because 'amount' is cast to (int) in XenditPHPClient::createInvoice.

Just wondering, is there a configuration to allow payment with decimal number. Do you have a patch for it, or we need to upgrade to the latest version(2.17)? Thanks

**Comment by xen-HendryZheng** [comment]
Hi @tannguyen-iprice Thanks for highlighting ! We will look into this and update you soonest.

**Comment by xen-HendryZheng** [comment]
Hi @tannguyen-iprice We just got affirmation that for IDR Invoice, the 2 decimals behind will be truncated. Unless for PHP (Philiphines), the decimals are being kept. 

Hope that clarifies :)

**Comment by tannguyen-iprice** [comment]
Hi @xen-HendryZheng,

Thanks for checking our issue. I'm not sure about this part "Unless for PHP (Philiphines), the decimals are being kept", so it means current version is working well, no need to check issue on version 1.4, and we should upgrade to the latest version, right?

Maybe I haven't shared enough context to you, we are using xendit-php version 1.4. Here is the sample data that we called xendit-php to create invoice.

```
        //private XenditPHPClient $client;
        return $this->client->createInvoice(
            'devgoreward72',
            1098.5,
            'dummymail@gmail.com',
            'Payment for Galaxy A12 NTC 1 year official warranty at Lazada',
            [
                'currency' => 'PHP',
                'should_send_email' => '',
                'invoice_duration' => 120,
                'success_redirect_url' => 'https://dev-gorewards-ph.iprice.mx/checkout-success/',
                'failure_redirect_url' => 'https://dev-gorewards-ph.iprice.mx/checkout-fail/',
            ]
        );
```

But the amount is being rounded in "createInvoice" function here 
![image](https://user-images.githubusercontent.com/86584674/148057593-a7aa1374-d228-4e5a-bd4a-62754b3043e0.png)

Link reference: https://github.com/xendit/xendit-php/blob/462ef3e13003039a522177bb576808f1bb16fe86/src/XenditPHPClient.php#L20


I think there are some options for us:
1. Apply the patch from you
2. Upgrade to the latest version(if the latest version does not have the same issue)
3. We are missing some configurations(need your advice)

Thanks

**Comment by xen-HendryZheng** [comment]
Hi @tannguyen-iprice 
Apparently for IDR, currently xendit does not support 2 decimal points. 
Refer attached,
![image](https://user-images.githubusercontent.com/90175540/148069260-de199c3c-a80e-4c62-8caf-9fce963d2753.png)

So far we only support for PH (PHP currency) for the decimal points.

As for the version,
It is always recommended to use latest SDK version as it contains our latest updates and fix.

Hope it clarifies :)

**Comment by xen-HendryZheng** [comment]
Hi @tannguyen-iprice 

Could you try the latest version of our SDK at [v2.17.1](https://github.com/xendit/xendit-php/releases/tag/2.17.1)

[And refer to the code below:
](https://github.com/xendit/xendit-php/blob/2.17.1/examples/InvoiceExample.php)```
use Xendit\Xendit;

require 'vendor/autoload.php';

Xendit::setApiKey('xnd_development_3YaHDmp8Wo5mDpZZi7y3jMFlIR9BZNgeP1L0wMfKHQDKxq6ZFAVOlfLmf1WGr88');

$params = ['external_id' => 'demo_1234992211',
    'payer_email' => 'hendry@xendit.co',
    'currency' => 'PHP',
    'description' => 'Trip to Bali',
    'amount' => 23545.50
];

$createInvoice = \Xendit\Invoice::create($params);
var_dump($createInvoice);
```

for PHP Currency, there's no validation or casting to int for the amount.

Do try it out and let us know :)

**Comment by luminto17** [comment]
<img width="1890" alt="Screen Shot 2022-01-04 at 21 29 15" src="https://user-images.githubusercontent.com/9628847/148074105-935f0856-cd0b-47bd-bfef-66742ba2d352.png">
Hi @tannguyen-iprice , additional context on top of Hendry's suggestion above, we have tried to make an Invoice w/ decimal using the latest version, and it was successfully created alongside the decimal (screenshot attached)

Let us know how's the result on your end :)

**Comment by luminto17** [comment]
Hi @tannguyen-iprice , additional context on top of Hendry's suggestion above, we have tried to make an Invoice w/ decimal using the latest version, and it was successfully created alongside the decimal (screenshot attached)

<img width="1890" alt="Screen Shot 2022-01-04 at 21 29 15" src="https://user-images.githubusercontent.com/9628847/148074370-03fccbc5-aa49-4eed-ac48-056a02402eee.png">

Let us know how's the result on your end :)

**Comment by tannguyen-iprice** [comment]
Hi @xen-HendryZheng , @luminto17 ,
Thank you for the enthusiastic support! We are planning to upgrade the extension to v2.17.1, thanks
