### ISSUE TITLE
Create Disbursement Response Error Code unCatchable

### ISSUE THREAD

**Issue by indragunawan82** [xendit/xendit-php#173]
Step to Reproduce :
Create Disbursement Request with this payload : 
  "external_id" => "freetext"
  "amount" => "100000"
  "bank_code" => "Dummy Bank"
  "account_holder_name" => "freetext"
  "account_number" => "085611111111"
  "description" => "freetext"
  

 Result should be : 
![image](https://user-images.githubusercontent.com/9045625/153137822-842544ba-a067-4655-bb69-eebe6b0a7b72.png)

i tried to catch the error response  by using this :
![image](https://user-images.githubusercontent.com/9045625/153137909-7bb21022-1f77-40a4-b571-f6a7967cab63.png)

the response still same :
![image](https://user-images.githubusercontent.com/9045625/153137965-cdabb3e9-d3ce-4f56-a419-4975dc7d91fc.png)

expected response/result : should be "xx"

**Comment by adityarx** [comment]
Hi @indragunawan82, a bit of a late response, but we're not quite sure about the dd() function. I believe you should be able to catch the exception raised by creating the disbursement and handle the paymernt from there.
