### ISSUE TITLE
That bank code is not currently supported

### ISSUE THREAD

**Issue by raf-lii** [xendit/xendit-php#177]
halo, disini saya mencoba untuk membuat pembayaran menggunakan virtual account menggunakan

```
        $params = [
            'external_id' => $oid,
            'bank_code' => $code,
            'name' => 'TopupSkuy',
            'is_closed' => true,
            'expected_amount' => $harga,
            'expiration_date' => Carbon::create(now())->addDay(),
            'is_single_use' => true
        ];

        $createVA = \Xendit\VirtualAccounts::create($params);
        return $createVA;

```

akan tetapi ketika saya jalankan menggunakan code bank seperti (BRI, BNI, SAHABAT_SAMPOERNA) tidak ada error yang muncul tetapi jika menggunakan (MANDIRI/PERMATA) saya mendapatkan pesan `That bank code is not currently supported` padahal saya sudah mengikut bank_code sesuai dengan yang ada di dokumentasi [Xendit](https://developers.xendit.co/api-reference/#virtual-account-object) & juga status metode pembayaran tersebut sudah aktif

**Comment by luminto17** [comment]
Selamat pagi @raf-lii , apakah bisa dikonfirmasi eror tersebut muncul di Test mode atau Live mode? Dan apakah boleh share contoh request payload yang mendapatkan eror tersebut untuk kami telusuri lebih lanjut?

Terima kasih

**Comment by raf-lii** [comment]
@luminto17 untuk error tersebut muncul di live mode, dan contoh request payload nya :
```
        $params = [
            'external_id' => $orderId,
            'bank_code' => 'Mandiri',
            'name' => $name,
            'is_closed' => true,
            'expected_amount' => $harga,
            'expiration_date' => Carbon::create(now())->addDay(),
            'is_single_use' => true
        ];

        $createVA = \Xendit\VirtualAccounts::create($params);
        return $createVA;
```

**Comment by luminto17** [comment]
selamat siang @raf-lii , untuk informasi diatas masih dalam bentuk sampel kode ya
Untuk request payload nya berupa data yang dikirim pada request, seperti contoh `external_id: INV-123193010, bank_code: MANDIRI, name: Luminto` dan lain sebagainya
Atau mungkin bisa dibantu alamat email yang terdaftar pada akun Xendit?
Terima kasih

**Comment by raf-lii** [comment]
@luminto17 untuk emailnya pspayment99@gmail.com

**Comment by uzzielpelawak** [comment]
halo saya juga menemukan masalah yah sama yah, 

payload yang saya kirim 
`["external_id"]=> string(17) "pixie-18-4EqBYQeK" ["bank_code"]=> string(7) "MANDIRI" ["name"]=> string(18) "PixieStore Payment" `

**Comment by cintarmynti** [comment]
> @luminto17 untuk emailnya [pspayment99@gmail.com](mailto:pspayment99@gmail.com)

halo kak ini sudah solved belum ya, saya mengalami kendala yang sama

**Comment by uzzielpelawak** [comment]
> 

chat customer service nya kak, kemaren ID nya belum di aktifkan soalnya.

**Comment by adityarx** [comment]
Closing this issue as solved
