### ISSUE TITLE
callback problem

### ISSUE THREAD

**Issue by hermans** [xendit/xendit-php#178]
Halo, saya lagi proses integrasi dengan xendit (OVO), tapi kenapa callback tidak masuk ke path url yg sudah saya input di setting xendit ya ? jadinya order status di database kami tidak terupdate

error yang tampil:
![image](https://user-images.githubusercontent.com/938767/156742240-44b758c3-ebd8-4ea9-b7f7-350c3e18eda5.png)

setting:
![image](https://user-images.githubusercontent.com/938767/156742411-41723b5d-cacb-4f7e-82c3-b27aa4c83807.png)

selain itu saya sudah coba cara untuk set callback dari script php
~~~
$callbackUrlParams = [
    'url' => 'https://test.test/callback/xendit'
];
$callbackType = 'invoice';
$setCallbackUrl = \Xendit\Platform::setCallbackUrl($callbackType, $callbackUrlParams);
~~~

**Comment by luminto17** [comment]
Selamat pagi @hermans , setelah kami melakukan pengecekan, kami mendapatkan `SSL Error: unable to verify the first certificate` menggunakan Postman dan `Unable to connect` menggunakan https://www.digicert.com/help/

Mungkin bisa di bantu cek apakah konfigurasi sertifikat nya sudah benar? Terima kasih

![Screen Shot 2022-03-07 at 10 31 02](https://user-images.githubusercontent.com/9628847/156963194-d62240af-965f-48c8-bf03-70f82c74bff6.png)
