### ISSUE TITLE
Error ketika create invoice

### ISSUE THREAD

**Issue by barraaaa** [xendit/xendit-php#184]
saya mendapatkan pesan error ketika menggunakan `\Xendit\Invoice::create($params);`

`exception: "ErrorException"
file: "/laravel/vendor/xendit/xendit-php/src/HttpClient/GuzzleClient.php"
line: 168
message: "Undefined index: message"`

**Comment by helloeyesimple** [comment]
@barraaaa saya juga mendapatkan pesan tersebut, bagaimana cara mengatasinya?
