### ISSUE TITLE
check balance error "Ledger accounts found for both IDR and PHP currency, we don't know which to pick"

### ISSUE THREAD

**Issue by capcaicah** [xendit/xendit-php#191]
hi xendit team, 

when we call balance, we got error Ledger accounts found for both IDR and PHP currency, we don't know which to pick.

I check your documentation, but its not updated about legder account.

after I investigation, we found you add new query string currency(IDR / PHP) for legder

so, in balance.php i modify from :

$url = '/balance?account_type=' . $account_type 

to $url = '/balance?account_type=' . $account_type.'&currency=IDR';

please update to this code so we not get error

thanks

**Comment by adityarx** [comment]
Closed as fixed!
