### ISSUE TITLE
Xendit.card.createToken authentication failed with reason AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by hlc94** [xendit/xendit-php#195]
The xendit.js createToken method always fails with failure reason "AUTHENTICATION_FAILED". testing on https://js.xendit.co/test_tokenize.html with the same development/test mode public key also fails with the same reason.

**Comment by adityarx** [comment]
Hello @hlc94, our apologies for this. We're keeping issues on GitHub reserved for active bugs and feature requests for our PHP SDK, so we encourage you to have a look at our Docs (https://docs.xendit.co/) or ask for help through the chatbot. Cheers and sorry we couldn't be of help~
