### ISSUE TITLE
Callback Virtual Akun

### ISSUE THREAD

**Issue by stenlyysamberi** [xendit/xendit-php#196]
**#ASK**

kalo simulasi pembayaraan dengan virtual akun menggunakan bank_account_number = xxxxxx164313 (https://api.xendit.co/pool_virtual_accounts/simulate_payment) gk muncul di report callback ya? tapi jika menggunakan external_id = xxx8989 dengan enpoint (https://api.xendit.co/callback_virtual_accounts/external_id=IC-1667103700/simulate_payment) muncul di report callback, apakah ada salah config?

![pay](https://user-images.githubusercontent.com/85916838/198862879-030a1209-f039-4e84-8a2d-ff8eba4ff884.png)

**Comment by adityarx** [comment]
Hello @stenlyysamberi, apologies for the trouble and the late response. We're keeping issues on GitHub reserved for active bugs and feature requests for our PHP SDK, so we encourage you to have a look at our Docs (https://docs.xendit.co/) or ask for help through our help page https://www.xendit.co/en/contact/. Cheers and sorry we couldn't be of help~
