### ISSUE TITLE
Callback E-Wallets

### ISSUE THREAD

**Issue by husna3305** [xendit/xendit-php#197]
Setting untuk callback sukses melalui e-wallet tidak masuk 
![image](https://user-images.githubusercontent.com/37904539/200265907-b6779b63-60ff-4857-a99c-7a67ef30ad4e.png)

**Comment by adityarx** [comment]
Hello @husna3305, apologies for the trouble and the late response. We're keeping issues on GitHub reserved for active bugs and feature requests for our PHP SDK, so we encourage you to have a look at our Docs (https://docs.xendit.co/) or ask for help through our help page https://www.xendit.co/en/contact/. Cheers and sorry we couldn't be of help~
