### ISSUE TITLE
"Could not find and update PENDING invoice" error

### ISSUE THREAD

**Issue by whousehomestay** [xendit/xendit-php#200]
It happens when we try to change the status of an invoice (payment link) to expired, while maybe on xendit, the invoice's status has been expired. Maybe we can prevent this by checking the status first, if it's pending then expired request is sent.

A bit of code to reproduce this error:
do:
$expireInvoice = Invoice::expireInvoice($invoiceId);
on expired invoice.

**Comment by adityarx** [comment]
Hello @whousehomestay for implementation assistance please have a read through our Docs (https://docs.xendit.co/) or ask for help using our site's chatbot. Thanks! 🙏
