### ISSUE TITLE
Is any update to support the new Payouts to replace old Disbursement method

### ISSUE THREAD

**Issue by yanuaraditia** [xendit/xendit-php#201]
According to the new api reference updates [https://developers.xendit.co/api-reference/#payouts](https://developers.xendit.co/api-reference/#payouts) the new Payouts API is an updated version of the existing Disbursements API product where users are able to send money at scale.

## SDK Changed
- The old sdk the `Payout` method still represents **Payout Links** feature which already replaced in current update

I've communicate with Xendit support but still no solutions for this case

**Comment by adityarx** [comment]
Closing this issue as resolved! Thanks~
