### ISSUE TITLE
Payment menggunakan ovo tervalidasi sesaat setelah charge

### ISSUE THREAD

**Issue by shuujin23** [xendit/xendit-php#203]
Halo,

Saya sedang coba menggunakan OVO untuk pembayaran pada Xendit API. Namun saya coba di test env sesaat setelah charge, webhook saya menerima notifikasi pembayaran sukses, padahal belum melakukan pembayaran sama sekali. Di production pun sama seperti itu, tidak ada notifikasi masuk sama sekali ke handphone dan webhook saya menerima notifikasi bahwa pembayaran sukses.

Mohon masukannya, apakah ada kesalahan pada saat saya implementasi atau bagaimana ya?
Terima kasih.

**Comment by shuujin23** [comment]
Informasi Tambahan.
Saya menerima callback seperti ini ketika charge success. 
![image](https://user-images.githubusercontent.com/8181423/221346788-1331a63f-f373-4d0c-ba94-3d0d9bb06569.png)

**Comment by adityarx** [comment]
Hello @shuujin23 for implementation assistance please have a read through our Docs (https://docs.xendit.co/) or ask for help using our site's chatbot. Thanks! 🙏
