### ISSUE TITLE
Invalid Value for Enum '\Xendit\Invoice\BankCode'

### ISSUE THREAD

**Issue by IMYELI** [xendit/xendit-php#211]
I got this error message when I tried to create an invoice.
![image](https://github.com/xendit/xendit-php/assets/74661051/b3e56b89-f5b0-4940-84b9-4c8047d0d47d)

I tried doing as instructed in this readme file
https://github.com/xendit/xendit-php/blob/master/docs/Invoice/InvoiceApi.md#createInvoice

here is my code
![image](https://github.com/xendit/xendit-php/assets/74661051/a1d06892-3cfc-4144-8b49-7eed57b989d4)

I tried tracking where it went wrong using dd() and I found out that it is in line 212 of InvoiceApi.php from the ObjectSerializer::deserialize.
![image](https://github.com/xendit/xendit-php/assets/74661051/29210b95-3f39-46a2-b8d6-11001bceba62)

Can someone help me?

**Comment by adityarx** [comment]
Hello @IMYELI apologies on this and thank you for bringing this up to us. I've raised this to the relevant team and they're working to update the bank codes now 🙏

**Comment by IMYELI** [comment]
Thankyou for the response. I'll wait for follow up regarding this matter.

**Comment by adityarx** [comment]
@IMYELI thanks for your patience, could you upgrade to v3.2.0? We have pushed the fix to this version.

**Comment by adityarx** [comment]
Closing this as I assume the fix works already 🙏
