### ISSUE TITLE
Package not compatibele with documentation on xendit docs api reference

### ISSUE THREAD

**Issue by Akhmami** [xendit/xendit-php#212]
documentasi pada api reference https://developers.xendit.co/api-reference masih menggunakan versi 2.19 belum di update sesuai versi terbaru package

**Comment by adityarx** [comment]
Halo @Akhmami , can we refer you to the documentation here https://github.com/xendit/xendit-php#documentation. There are code snippets if you can click into the API you plan to use

**Comment by Akhmami** [comment]
I don't understand some parts because the documentation is not clear

**Comment by adityarx** [comment]
@Akhmami Apologies on that! We do plan to add more examples to make the documentation clearer, but I think it's out of scope for the issues session. Could you contact our support through this [link](https://www.xendit.co/en/contact/)? Our customer support team will be happy to give more specific answers to the questions you may have.
