### ISSUE TITLE
Provide an API Endpoint to get all user subscription

### ISSUE THREAD

**Issue by dongumayagay** [xendit/xendit-php#214]
on creating a subscription plan. the customer_id is required means it is somehow connected to the subscription plan and the customer.

it will be helpful for us xendit user for register a plan to a customer(creating plan) and then just fetch the customers' plan.

as the thing now we have to keep track of all those connection on our end. it's redundant as per xendit already have it and it's simpler to have only once source of truth. to keep the data integrity

**Comment by adityarx** [comment]
Hii @dongumayagay is this an additional feature request on top of your previous request of adding subscriptions to the SDK?

**Comment by dongumayagay** [comment]
It's not. we decided to implement the subscription without the sdk. as per opening this issue here. IDK where is the better place to submit MB.

but yeah i believe it's easier for merchants to manage subscriptions of the user is there is provided api that we are just going to provide the customer id or customer reference if and will get the customers subscription. its better ergonomics.

as per my previous request i still want to for the SDKs to support the new features as its hard to go back and for from documentation and editor to check available paramaters and return value. its helpful to have sdk for helping with intellisense and in code editor documentation of methods, parameter and return value.

**Comment by adityarx** [comment]
Ah ok, so this is a separate feature request for an API on Subscriptions (not necessarily SDK) that allows listing subscriptions by customer_id. Could you reach out to us through your Account Manager? That will help us link you with the correct team that can respond.

Issues here are mostly for bugs and feature requests on the SDKs 🙏
