### ISSUE TITLE
Failed webhook send, but not redirected to failure redirect url

### ISSUE THREAD

**Issue by rahmrny12** [xendit/xendit-php#221]
I want to redirect my invoice to after the payment was a success. But, then my order status in database won't updated like usual. After checking on webhook detail, it is sent but the response is 404 because the ngrok server url was expired.
I confused that the page wont redirected to _failure_redirect_url_, but still _success_redirect_url_ instead. Is _failure_redirect_url_ only triggered after spesific event only?

![image](https://github.com/xendit/xendit-php/assets/77597283/238ffc47-b693-4f74-85ed-376c92f44307)

![image](https://github.com/xendit/xendit-php/assets/77597283/5cb5273b-5c8b-4463-9f8d-077a14dd32a9)

**Comment by adityarx** [comment]
Hi @rahmrny12, thanks for using Xendit! For integration related questions, I think you'd be best to go to our [help page](https://help.xendit.co/hc/en-us) and reach out to our customer support through email or WhatsApp.

We're reserving issues on the repository to SDK feature requests or bugs 🙏
