### ISSUE TITLE
Parameter Success Redirect URL

### ISSUE THREAD

**Issue by kiddyxyz** [xendit/xendit-php#34]
I want to redirect my invoice to after the payment was a success.
I don't see any parameter of success redirect URL, also I try to CURL and doesn't see the response of success redirect URL. What should I do?

![Screenshot from 2019-07-04 21-26-36](https://user-images.githubusercontent.com/19512705/60673675-7bc66180-9ea2-11e9-8e74-913fe0043304.png)

**Comment by stanleynguyen** [comment]
Hey @kiddyxyz you can now pass `success_redirect_url` and `failure_redirect_url` as params to creating invoice with v2 release of this library. I'm closing this issue
