### ISSUE TITLE
Package requirements not compatible with Laravel

### ISSUE THREAD

**Issue by aanred** [xendit/xendit-php#55]
This package requirement in your composer file

`"vlucas/phpdotenv": "^4.1"`

is not compatible with Laravel. I want to use it in my app that uses Laravel 5.5. I've also tested with the latest Laravel it won't install.

Can you please update your package requirements so that it can be more compatible globally? Tks.

**Comment by stanleynguyen** [comment]
@aanred Nice catch. Thank you so much. v2.0.0 is being tagged to a wrong commit with `phpdotenv` declared as `require`. We will get it fixed asap. In the mean time, you can use https://packagist.org/packages/xendit/xendit-php-clients#dev-master version

**Comment by stanleynguyen** [comment]
This has been fixed in the latest release https://packagist.org/packages/xendit/xendit-php#2.0.2
Thanks @aanred for pointing it out
