### ISSUE TITLE
Error Class 'Dotenv\Dotenv' not found

### ISSUE THREAD

**Issue by rizki5411** [xendit/xendit-php#66]
Tolong dibantu saya lagi integrasikan ovo payment dengan library v2 tapi malah terjadi error,
`Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in C:\xampp\htdocs\xendit\tes.php:19 Stack trace: #0 {main} thrown in C:\xampp\htdocs\xendit\tes.php on line 19`

Berikut code saya
```
use Dotenv\Dotenv;
use Xendit\Xendit;

require 'vendor/autoload.php';

$dotenv = Dotenv::createImmutable(__DIR__ . '/..');
$dotenv->load();
Xendit::setApiKey(getenv('xnd_production_aJgisgZJk9tc4bd5IM0moxxxx'));

$ovoParams = [
    'external_id'	=> 'demo_' . time(),
    'amount'		=> 32000,
    'phone'			=> '081298498259',
    'ewallet_type'	=> 'OVO'
];

try {
    $createOvo = \Xendit\EWallets::create($ovoParams);
    var_dump($createOvo);
} catch (\Xendit\Exceptions\ApiException $exception) {
    var_dump($exception);
}

$getOvo = \Xendit\EWallets::getPaymentStatus($ovoParams['external_id'], 'OVO');
var_dump($getOvo);
```
Code diatas saya ambil dari folder example dari repo github disini.

**Comment by edwinyoyada** [comment]
halo @rizki5411 apakah sudah install `DotEnv`nya? boleh share composer.json nya?

**Comment by ErvanAdetya** [comment]
Halo @rizki5411 di code nya
`Xendit::setApiKey(getenv('xnd_production_aJgisgZJk9tc4bd5IM0moxxxx'));`

jika ingin tidak menggunakan `dotenv` bisa langsung seperti ini
`Xendit::setApiKey('xnd_production_aJgisgZJk9tc4bd5IM0moxxxx');`
tanpa memanggil fungsi getenv.

Jika mau menggunakan `.env` bisa di set file `.env` nya dengan 
`SECRET_API_KEY=<your api key here>`
Sebagai isinya, dan fungsi setApiKey nya di panggil dengan cara
`Xendit::setApiKey(getenv('SECRET_API_KEY'));`

**Comment by rizki5411** [comment]
> 
> 
> Halo @rizki5411 di code nya
> `Xendit::setApiKey(getenv('xnd_production_aJgisgZJk9tc4bd5IM0moxxxx'));`
> 
> jika ingin tidak menggunakan `dotenv` bisa langsung seperti ini
> `Xendit::setApiKey('xnd_production_aJgisgZJk9tc4bd5IM0moxxxx');`
> tanpa memanggil fungsi getenv.
> 
> Jika mau menggunakan `.env` bisa di set file `.env` nya dengan
> `SECRET_API_KEY=<your api key here>`
> Sebagai isinya, dan fungsi setApiKey nya di panggil dengan cara
> `Xendit::setApiKey(getenv('SECRET_API_KEY'));`

Apakah dontev penting mas?

**Comment by rizki5411** [comment]
> 
> 
> halo @rizki5411 apakah sudah install `DotEnv`nya? boleh share composer.json nya?

```
{
    "require": {
        "xendit/xendit-php": "^2.3"
    }
}
```

**Comment by rizki5411** [comment]
![image](https://user-images.githubusercontent.com/31713769/79945883-03fd0e00-8499-11ea-9f1f-8b11593aa43a.png)

Ada yg bisa bantu saya? pas saya masukan ke function bagian `use Xendit\Xendit`; error, saya taro diluar function malah error semua controllernya

**Comment by edwinyoyada** [comment]
halo @rizki5411 , dotenv bisa dipakai untuk set environment variables, jadi kalau mas punya data kaya API key atau url yang bisa beda2 untuk tiap env, mas bisa pake untuk ngebedain juga termasuk mana yang mau di load.. jadi ga perlu ganti2 tiap kali mau deploy atau testing..

bisa baca2 ini mas: https://www.malasngoding.com/konfigurasi-dasar-pada-laravel/

**Comment by rizki5411** [comment]
> 
> 
> halo @rizki5411 , dotenv bisa dipakai untuk set environment variables, jadi kalau mas punya data kaya API key atau url yang bisa beda2 untuk tiap env, mas bisa pake untuk ngebedain juga termasuk mana yang mau di load.. jadi ga perlu ganti2 tiap kali mau deploy atau testing..
> 
> bisa baca2 ini mas: https://www.malasngoding.com/konfigurasi-dasar-pada-laravel/

Ok masa saya putuskan gk pake dontev, tapi mohon mas 1 masalah lagi, saya gk bisa gunakan `use Xendit\Xendit` dalam function di controller. Harus digimanakan ya?

**Comment by edwinyoyada** [comment]
halo mas, apakah mas menggunakan class di PHP nya?

**Comment by rizki5411** [comment]
> 
> 
> halo mas, apakah mas menggunakan class di PHP nya?

iya, kebetulan saya gunakan CodeIgniter, dan itu dlm Controllernya

**Comment by edwinyoyada** [comment]
halo mas, untuk CI, saya udah agak lupa sih, tapi bisa follow guide ini: https://www.petanikode.com/codeigniter-composer/

karna CI ga pake namespacing, maka mas ga bisa pake `use` jadi harus di-initiate dulu

**Comment by stanleynguyen** [comment]
Stale

**Comment by fandiananta** [comment]
Message: Class "Xendit\Xendit" not found

gimana ya :"(
