### ISSUE TITLE
Perubahan API KEY development ke API KEY production

### ISSUE THREAD

**Issue by AndhikaAdjie** [xendit/xendit-php#71]
saya mau bertanya, awalnya saya memasang api key development pada aplikasi saya untuk menggunakan api xendit lalu ketika saya mengubah api key development tersebut menjadi api key production semua transaksi saya seperti virtual account dan ewallet ovo tidak masuk ke live mode tetapi malah masuk ke test mode, itu kenapa ya ? 
saya mengakses api xendit menggunakan library xendit-php ini

**Comment by kevindavee** [comment]
Halo @AndhikaAdjie , bisa share code snippet dari implementasinya supaya kami bisa bantu untuk cek. Untuk value API key nya nanti jangan di share kesini ya.

**Comment by AndhikaAdjie** [comment]
<?php
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/MY_model.php';
require APPPATH . '../vendor/autoload.php';
use Xendit\Xendit;
class Payment_model extends MY_Model {

    public function __construct()
	{
		parent::__construct();
		header("Access-Control-Allow-Origin: *");
		Xendit::setApiKey('xnd_production_NVPey1eOsE5puhMqVVxxxxxx');

    }

    function saveVaPayment($dataInvoice)
	{
        $expired = false;
        $diskon = 0;
		$this->db->where('durasi.id_durasi', $dataInvoice['id_durasi']);
		$checkData = $this->db->get('durasi')->row();
		//cek user 
		if (!empty($checkData)) {
            $tgl_sekarang = date('Y-m-d h:i:s');
            $dataInvoice['expiration'] = date('Y-m-d h:i:s', strtotime('+'.$checkData->bataswaktu.' month', strtotime($tgl_sekarang)));
            $dataInvoice['expired_at'] = date('Y-m-d h:i:s', strtotime('+1 day', strtotime($dataInvoice['created_at'])));
            $harga_durasi = $checkData->harga_durasi;

			$this->db->where('fakultas.id_fakultas', $dataInvoice['id_fakultas']);
		    $dataFakultas = $this->db->get('fakultas')->row();
			if($dataFakultas){
                $harga_fakultas = $dataFakultas->harga;

                if($dataInvoice['id_promo']!=NULL){
                    $this->db->where('voucher.id_voucher', $dataInvoice['id_promo']);
                    $dataPromo = $this->db->get('voucher')->row();
                    $diskon = $dataPromo->diskon;
                    if(strtotime('now') > strtotime($dataPromo->expired_at)){
                        $expired = true;
                    }
                }
                else if($dataInvoice['id_referal']!=NULL){
                    $this->db->where('voucher.kode_unik', 'KODE-PREMIUM');
                    $dataPromo = $this->db->get('voucher')->row();
                    $diskon = $dataPromo->diskon;
                    $poin = $dataPromo->poin;
                }

                if($expired == false){
                    $dataInvoice['total_diskon'] = $diskon;
                    $dataInvoice['total_bayar'] = $harga_fakultas + $harga_durasi - $diskon;

                    $this->db->select('nama_payment, tipe');
                    $this->db->where('id_payment', $dataInvoice['id_payment']);
                    $payment = $this->db->get('payment_method')->row();
                    
                    $this->db->select('norek_bank, nama_pemilik, fee');
                    $this->db->where('id_payment', $dataInvoice['id_payment']);
                    $this->db->where('id_daftarbank', $dataInvoice['id_bank']);
                    $bank = $this->db->get('daftar_bank')->row();
                    $dataInvoice['total_bayar'] += $bank->fee;
                    
                    $this->db->select('member.email, member.nama');
                    $this->db->join('member', 'member.id_member=user.id_member');
                    $this->db->where('user.id_user', $dataInvoice['id_user']);
                    $user = $this->db->get('user')->row();

                    $params = ["external_id" => "VA_fixed-".(time()+$dataInvoice['total_bayar']),
                        "bank_code" => "MANDIRI",
                        "name" => $user->nama,
                        "expected_amount" => $dataInvoice['total_bayar'],
                        "is_closed" => true,
                        "is_single_use" => true
                    ];

                    $createVA = \Xendit\VirtualAccounts::create($params);
                    $dataInvoice['va_number'] = $createVA['account_number'];

                    $insertInvoice = $this->db->insert('invoice', $dataInvoice);
                    if($insertInvoice){
                        // if($dataInvoice['id_referal']!=NULL){
                        //     $this->db->query("UPDATE user SET poin=poin+$poin WHERE id_user=".$dataInvoice['id_referal']."");
                        // }

                        $this->db->where('fakultas_user.id_user', $dataInvoice['id_user']);
                        $this->db->where('fakultas_user.id_fakultas', $dataInvoice['id_fakultas']);
                        $checkFakultas = $this->db->get('fakultas_user')->row();
                        if(empty($checkFakultas)){
                            $data = array('id_user'=>$dataInvoice['id_user'],
                                            'id_fakultas'=>$dataInvoice['id_fakultas']);
                            $this->db->insert('fakultas_user', $data);
                        }
                        
                        $dataEmail = array('total_pembayaran'=> $dataInvoice['total_bayar'],
                                            'metode_pembayaran'=> $payment->nama_payment,
                                            'norek'=> $dataInvoice['va_number'],
                                            'pemilik_akun'=> $bank->nama_pemilik,
                                            'status_pembayaran'=> 'Menunggu Pembayaran',
                                            'tgl_checkout'=> date('j F Y'),
                                            'waktu_checkout'=> date('H.i'),
                                            'tgl_expired'=> date("j F Y", strtotime($dataInvoice['expired_at'])),
                                            'waktu_expired'=> date("H.i", strtotime($dataInvoice['expired_at'])),
                                            'durasi'=> $checkData->nama_durasi,
                                            'harga_durasi'=> $checkData->harga_durasi+$dataFakultas->harga,
                                            'email'=> $user->email,
                                            'promo'=> $diskon,
                                            'fee_bank'=> $bank->fee);
                        $this->sendNotificationPayment($dataEmail);

                        $this->db->select('id_invoice');
                        $this->db->order_by('id_invoice', 'DESC');
                        $this->db->limit(1);
                        $invo = $this->db->get('invoice')->row();

                        $dataOut = array('id_payment'=> $invo->id_invoice,
                                        'message'=> "Pembayaran Berhasil dilakukan",
                                        'data xendit'=> $createVA);
                        $output['result'] = $dataOut;
                        $output['status'] = true;
                    }
                    else {
                        $output['status'] = false;
                        $output['error'] = "terjadi kesalahan saat menyimpan data";
                    }
                }
                else {
                    $output['status'] = false;
                    $output['error'] = "Kode Promo sudah kadaluarsa";
                }
			}
			else {
				$output['status'] = false;
				$output['error'] = "terjadi kesalahan saat mengecek data fakultas";
			}
		}else{
			$output['status'] = false;
			$output['error'] = "Durasi tidak ditemukan";
		}
		return $output;
    }

seperti ini code saya

**Comment by AndhikaAdjie** [comment]
seperti ini code saya

defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/MY_model.php';
require APPPATH . '../vendor/autoload.php';
use Xendit\Xendit;
class Payment_model extends MY_Model {

    public function __construct()
	{
		parent::__construct();
		header("Access-Control-Allow-Origin: *");
		Xendit::setApiKey('xnd_production_NVPey1eOsE5xxxxxxx');

    }
    function saveVaPayment($dataInvoice)
	{
        $expired = false;
        $diskon = 0;
		$this->db->where('durasi.id_durasi', $dataInvoice['id_durasi']);
		$checkData = $this->db->get('durasi')->row();
		//cek user 
		if (!empty($checkData)) {
            $tgl_sekarang = date('Y-m-d h:i:s');
            $dataInvoice['expiration'] = date('Y-m-d h:i:s', strtotime('+'.$checkData->bataswaktu.' month', strtotime($tgl_sekarang)));
            $dataInvoice['expired_at'] = date('Y-m-d h:i:s', strtotime('+1 day', strtotime($dataInvoice['created_at'])));
            $harga_durasi = $checkData->harga_durasi;

			$this->db->where('fakultas.id_fakultas', $dataInvoice['id_fakultas']);
		    $dataFakultas = $this->db->get('fakultas')->row();
			if($dataFakultas){
                $harga_fakultas = $dataFakultas->harga;

                if($dataInvoice['id_promo']!=NULL){
                    $this->db->where('voucher.id_voucher', $dataInvoice['id_promo']);
                    $dataPromo = $this->db->get('voucher')->row();
                    $diskon = $dataPromo->diskon;
                    if(strtotime('now') > strtotime($dataPromo->expired_at)){
                        $expired = true;
                    }
                }
                else if($dataInvoice['id_referal']!=NULL){
                    $this->db->where('voucher.kode_unik', 'KODE-PREMIUM');
                    $dataPromo = $this->db->get('voucher')->row();
                    $diskon = $dataPromo->diskon;
                    $poin = $dataPromo->poin;
                }

                if($expired == false){
                    $dataInvoice['total_diskon'] = $diskon;
                    $dataInvoice['total_bayar'] = $harga_fakultas + $harga_durasi - $diskon;

                    $this->db->select('nama_payment, tipe');
                    $this->db->where('id_payment', $dataInvoice['id_payment']);
                    $payment = $this->db->get('payment_method')->row();
                    
                    $this->db->select('norek_bank, nama_pemilik, fee');
                    $this->db->where('id_payment', $dataInvoice['id_payment']);
                    $this->db->where('id_daftarbank', $dataInvoice['id_bank']);
                    $bank = $this->db->get('daftar_bank')->row();
                    $dataInvoice['total_bayar'] += $bank->fee;
                    
                    $this->db->select('member.email, member.nama');
                    $this->db->join('member', 'member.id_member=user.id_member');
                    $this->db->where('user.id_user', $dataInvoice['id_user']);
                    $user = $this->db->get('user')->row();

                    $params = ["external_id" => "VA_fixed-".(time()+$dataInvoice['total_bayar']),
                        "bank_code" => "MANDIRI",
                        "name" => $user->nama,
                        "expected_amount" => $dataInvoice['total_bayar'],
                        "is_closed" => true,
                        "is_single_use" => true
                    ];

                    $createVA = \Xendit\VirtualAccounts::create($params);
                    $dataInvoice['va_number'] = $createVA['account_number'];

                    $insertInvoice = $this->db->insert('invoice', $dataInvoice);
                    if($insertInvoice){
                        // if($dataInvoice['id_referal']!=NULL){
                        //     $this->db->query("UPDATE user SET poin=poin+$poin WHERE id_user=".$dataInvoice['id_referal']."");
                        // }

                        $this->db->where('fakultas_user.id_user', $dataInvoice['id_user']);
                        $this->db->where('fakultas_user.id_fakultas', $dataInvoice['id_fakultas']);
                        $checkFakultas = $this->db->get('fakultas_user')->row();
                        if(empty($checkFakultas)){
                            $data = array('id_user'=>$dataInvoice['id_user'],
                                            'id_fakultas'=>$dataInvoice['id_fakultas']);
                            $this->db->insert('fakultas_user', $data);
                        }
                        
                        $dataEmail = array('total_pembayaran'=> $dataInvoice['total_bayar'],
                                            'metode_pembayaran'=> $payment->nama_payment,
                                            'norek'=> $dataInvoice['va_number'],
                                            'pemilik_akun'=> $bank->nama_pemilik,
                                            'status_pembayaran'=> 'Menunggu Pembayaran',
                                            'tgl_checkout'=> date('j F Y'),
                                            'waktu_checkout'=> date('H.i'),
                                            'tgl_expired'=> date("j F Y", strtotime($dataInvoice['expired_at'])),
                                            'waktu_expired'=> date("H.i", strtotime($dataInvoice['expired_at'])),
                                            'durasi'=> $checkData->nama_durasi,
                                            'harga_durasi'=> $checkData->harga_durasi+$dataFakultas->harga,
                                            'email'=> $user->email,
                                            'promo'=> $diskon,
                                            'fee_bank'=> $bank->fee);
                        $this->sendNotificationPayment($dataEmail);

                        $this->db->select('id_invoice');
                        $this->db->order_by('id_invoice', 'DESC');
                        $this->db->limit(1);
                        $invo = $this->db->get('invoice')->row();

                        $dataOut = array('id_payment'=> $invo->id_invoice,
                                        'message'=> "Pembayaran Berhasil dilakukan",
                                        'data xendit'=> $createVA);
                        $output['result'] = $dataOut;
                        $output['status'] = true;
                    }
                    else {
                        $output['status'] = false;
                        $output['error'] = "terjadi kesalahan saat menyimpan data";
                    }
                }
                else {
                    $output['status'] = false;
                    $output['error'] = "Kode Promo sudah kadaluarsa";
                }
			}
			else {
				$output['status'] = false;
				$output['error'] = "terjadi kesalahan saat mengecek data fakultas";
			}
		}else{
			$output['status'] = false;
			$output['error'] = "Durasi tidak ditemukan";
		}
		return $output;
    }

**Comment by kevindavee** [comment]
Untuk ganti value API key nya dibagian constructor @AndhikaAdjie ?

**Comment by AndhikaAdjie** [comment]
iya, saya tidak menggunakan dotenv

**Comment by ErvanAdetya** [comment]
Apakah di luar code ini ada fungsi yg meng overide api key atau set value API Key nya?

Boleh cba share data seperti external id yg di klaim ter create sebagai data development namun menggunakan live API Key?
Product team xendit akan bantu dengan pengecekan internal, apakah kesalahan terjadi pada request atau system internal.

**Comment by AndhikaAdjie** [comment]
untuk fungsi yang set value API KEY tidak ada, set value API KEY hanya di construct itu saja.

ini adalah data terakhir kemarin yang saya coba menggunakan live API Key tapi masuknya ke test API Key
{
    "is_closed": true,
    "status": "ACTIVE",
    "currency": "IDR",
    "owner_id": "5e79bdcefcdcf6064c3278f8",
    "external_id": "VA_fixed-1587981674",
    "bank_code": "MANDIRI",
    "merchant_code": "88908",
    "name": "Andri",
    "account_number": "889089999488727",
    "expected_amount": 4951,
    "is_single_use": true,
    "expiration_date": "2051-04-26T17:00:00.000Z",
    "created": "2020-04-27T08:38:43.789Z",
    "updated": "2020-04-27T08:38:45.176Z",
    "id": "5ea69a138991d51d76196955"
}

**Comment by ErvanAdetya** [comment]
Di request log xendit, kami menemukan request tersebut di buat menggunakan API Key development mode, dengan API Key dengan nama "api key".

Boleh dipastikan mas jika script yg yg di run merupakan script yg terbaru atau melakukan debug jika API Key yg terSet sudah betul API Key Production.

**Comment by AndhikaAdjie** [comment]
sudah saya cek API Key yang saya gunakan adalah API Key Production. Bisa dilihat di code saya yang diatas, saya sudah pakai xnd_production_xxxxxxxxx dan juga sudah saya pastikan di server saya sudah memakai API Key Production.

Jika ada perubahan API Key itu hanya merubah di bagian ini saja kan ?
Xendit::setApiKey('api-key');

ataukah ada perubahan di bagian lain ?

**Comment by AndhikaAdjie** [comment]
Sudah bisa masuk, ternyata ada typo/kurang beberapa digit di API Key nya.
Terima kasih atas jawaban nya.

**Comment by edwinyoyada** [comment]
halo @AndhikaAdjie apakah bisa cek ke servernya kembali dan pastikan bahwa codenya sudah updated?
