### ISSUE TITLE
Xendit::getHttpClient() must be an instance

### ISSUE THREAD

**Issue by holywingsindonesia** [xendit/xendit-php#74]
Halo saya sudah mengikuti contoh code yang diberikan,
setiap saya panggil request payment keluar error

`
Xendit::setApiKey(getenv("xnd_pro_*******"));
        
        $ovoParams = [
            'external_id' => 'demo_' . time(),
            'amount' => 32000,
            'phone' => '081298498259',
            'ewallet_type' => 'OVO'
        ];

        $createOvo = EWallets::create($ovoParams);
        var_dump($createOvo);
`

**Comment by edwinyoyada** [comment]
halo @holywingsindonesia,
terima kasih untuk report bug nya,
kami akan segera memperbaikinya,
untuk sementara bisa pakai versi berikut: https://packagist.org/packages/xendit/xendit-php#2.3.1

**Comment by edwinyoyada** [comment]
halo @holywingsindonesia,
bisa pakai versi berikut untuk yang terbaru ya: https://packagist.org/packages/xendit/xendit-php#2.4.1
terima kasih
