### ISSUE TITLE
unexpected '=' at ApiRequestor.php

### ISSUE THREAD

**Issue by holywingsindonesia** [xendit/xendit-php#76]
Error ketika production request payment

`[$rbody, $rcode, $rheaders] = $this->_httpClient()->sendRequest(`

HttpClient/GuzzleClient.php

`[$rbody, $rcode, $rheader] = $this->_executeRequest($opts, $url);`

**Comment by stanleynguyen** [comment]
Hi @holywingsindonesia Can I have your code snippet that is throwing this error?

**Comment by holywingsindonesia** [comment]
`Xendit::setApiKey(getenv('xnd_production_S****'));
        
        $danaParams = [
            'external_id' => 'holywings_' . time(),
            'amount' => 2000,
            'phone' => '082112884647',
            'expiration_date' => '2020-05-02T00:00:00.000Z',
            'callback_url' => 'https://devtakeaway.holywings.id/callbacks',
            'redirect_url' => 'https://devtakeaway.holywings.id/site/wew',
            'ewallet_type' => 'DANA'
        ];

        $createDana = \Xendit\EWallets::create($danaParams);
        var_dump($createDana);`

**Comment by stanleynguyen** [comment]
@holywingsindonesia Can I have your PHP version as well?

**Comment by holywingsindonesia** [comment]
ah sorry, i forget switch php version in server. Thank you

**Comment by stanleynguyen** [comment]
@holywingsindonesia Cool. Is this issue considered resolved then? Please let us know if you encounter any other issues

**Comment by holywingsindonesia** [comment]
i back to mode development when i request payment
get error `Xendit\Exceptions\ApiException
There was an error with the format submitted to the server.`

` Xendit::setApiKey(getenv('xnd_development_dsaTihlnl**'));
        
        $danaParams = [
            'external_id' => 'demo_' . time(),
            'amount' => 32000,
            'phone' => '081298498259',
            'expiration_date' => '2020-02-20T00:00:00.000Z',
            'callback_url' => 'https://my-shop.com/callbacks',
            'redirect_url' => 'https://my-shop.com/home',
            'ewallet_type' => 'DANA'
        ];

        $createDana = \Xendit\EWallets::create($danaParams);
        var_dump($createDana);`

**Comment by stanleynguyen** [comment]
@holywingsindonesia Your `expiration_date` seems to be the problem. It should be a date in the future, your current one is in the past (20 Feb 2020)

**Comment by stanleynguyen** [comment]
@holywingsindonesia Another possible cause for this API error is missing API key. You might be missing a call to `setApiKey`

**Comment by holywingsindonesia** [comment]
> @holywingsindonesia Your `expiration_date` seems to be the problem. It should be a date in the future, your current one is in the past (20 Feb 2020)

already change keep same

`Xendit::setApiKey(getenv('xnd_development_***'))`
this i already call setApiKey

**Comment by stanleynguyen** [comment]
@holywingsindonesia It should be `Xendit::setApiKey('xnd_development_***')` without `getenv`

**Comment by holywingsindonesia** [comment]
okay thank you, i will try at production type now

**Comment by holywingsindonesia** [comment]
get response Sender IP address is not whitelisted
but i already put the IP server at dashboard

`
Xendit::setApiKey('xnd_production_ShitOq***');
        
        $params = ["external_id" => "262**",
           "bank_code" => "BRI",
           "name" => "Cydh"
        ];
        
        $createVA = \Xendit\VirtualAccounts::create($params);
        var_dump($createVA);
        
        $id = $createVA['id'];

        $getVABanks = \Xendit\VirtualAccounts::getVABanks();
        var_dump($getVABanks);
        
        $getVA = \Xendit\VirtualAccounts::retrieve($id);
        var_dump($getVA);
        
        $updateParams = ["suggested_amount" => 10000];
        $updateVA = \Xendit\VirtualAccounts::update($id, $updateParams);
        var_dump($updateVA);
        
        $paymentID = "262**_591200000****";
        
        $getFVAPayment = \Xendit\VirtualAccounts::getFVAPayment($paymentID);
        var_dump($getFVAPayment);`

or something wrong with this code?

**Comment by stanleynguyen** [comment]
@holywingsindonesia Yes. To use Live API key, you have to whitelist your server's IP address in https://dashboard.xendit.co/settings/developers#ip-whitelists

**Comment by holywingsindonesia** [comment]
Already sir

![already](https://user-images.githubusercontent.com/58675946/80804277-dfaed900-8bde-11ea-8fdb-5fb47cfd7890.png)

**Comment by stanleynguyen** [comment]
@holywingsindonesia  It's probably incorrect 🤔 You can try running this command `curl https://ipinfo.io/ip` in your server to see what your server's public IP is

**Comment by holywingsindonesia** [comment]
try ping devtakeaway.holywings.id its same like whitelist IP

this dedicated server sir

**Comment by stanleynguyen** [comment]
Hi @holywingsindonesia I think you had a typo in your whitelisted IP in dashboard. The one set there is `103.28.148.68` while your actual IP is `103.28.148.86` (Notice the difference in the last 2 digits 68 vs 86

**Comment by holywingsindonesia** [comment]
ah im so sorry, last question

26215 59**000000000 - 26215 59**999999999

`["external_id" => "26215"

$paymentID = "26215_59**000000005";

`
That external and payment ID is right?

**Comment by stanleynguyen** [comment]
@holywingsindonesia I'm guessing you're using `getFVAPayment`. `payment_id` should be the value of `payment_id` in payload you get from your callback for VA payment.

**Comment by holywingsindonesia** [comment]
ah okay, i get callback
    "account_number": "2621559126407242xx",
its random generate? or i can make static number?

**Comment by stanleynguyen** [comment]
@holywingsindonesia  `payment_id` is unique to every payment so it can't be fixed. May I know what is that you're trying to achieve?

**Comment by holywingsindonesia** [comment]
okay thank you, i wanna make 1 user => 1 account VA
we wanna build takeaway service and with another method payment.

anyway thank you for you help.

**Comment by stanleynguyen** [comment]
Cool hope that was helpful for you @holywingsindonesia
