### ISSUE TITLE
The API key is forbidden to perform this request

### ISSUE THREAD

**Issue by msquareM** [xendit/xendit-php#84]
Hi ,
This is mani when i store credit card details throw below issue
"exception: "Xendit\Exceptions\ApiException"
file: "xendit/xendit-php/src/HttpClient/GuzzleClient.php"
line: 167
message: "The API key is forbidden to perform this request" "

mycode look like below
 in laravel :
Xendit::setApiKey('***hidden_development_key***');
$params = ['amount' => 1013.5];
$captureCharge = \Xendit\Cards::capture($request->authid,$params);

in js file :
Xendit.card.createToken({        
			amount: parseInt(totalAmt),      
			card_number: $('#card_number').val(),        
			card_exp_month: getMonth,        
			card_exp_year: $('#expire_year').val(),        
			card_cvn: $('#cvv_number').val() ,       
			is_multiple_use: true,        
		}, xenditResponseHandler);
...

**Comment by stanleynguyen** [comment]
@msquareM Please check if your API key has `Money-In Write` permission in https://dashboard.xendit.co/settings/developers#api-keys

**Comment by msquareM** [comment]
Hi @stanleynguyen  thankyou so much its working now but i have one more doubt
how to get saved card details using token ? please give any example

**Comment by stanleynguyen** [comment]
@msquareM may I know why you need to get card details and which details you are looking to retrieve? We use tokens so that the card details don't flow through your backend system, ensuring the payment process to be PCI-DSS compliant.

**Comment by msquareM** [comment]
@stanleynguyen  this is saved credit card concept that why i using Multiple-Use Token in xendit client side and i have two ids one is authid and another one is token

when i give token or auth id in server side look like below

Xendit::setApiKey('hidden_development_key');
$params = ['amount' => 1013.5];
$captureCharge = \Xendit\Cards::capture(**$request->authid**,$params);

throw below error
message": "Could not find credit card charge",
"exception": "Xendit\Exceptions\ApiException","

**Comment by stanleynguyen** [comment]
@msquareM You should be passing in the charge id as the first param for capturing credit card charges

**Comment by stanleynguyen** [comment]
@msquareM auth id and the token will only be needed at creating charge step

**Comment by msquareM** [comment]
@stanleynguyen  ok now i  first creating charge step
look like below code
Xendit::setApiKey('hidden_development_key');
$params = [
			    'token_id' => $request->xendittoken,
			    'external_id' => 'card_' . time(),
			    'authentication_id' => $request->authid,
			    'amount' => 1013.5,
			    'card_cvn' => '123',
			     'capture' => false
			];
		    $createCharge = \Xendit\Cards::create($params);
but throw below error
"message: "There was an error with the format submitted to the server.",…}
exception: "Xendit\Exceptions\ApiException""

**Comment by stanleynguyen** [comment]
@msquareM You're using default currency IDR so amount must be an integer

**Comment by msquareM** [comment]
@stanleynguyen ok i changed amount to integer but still get same error 
my code :
$params = [
			    'token_id' => $request->xendittoken,
			    'external_id' => 'card_'.time(),
			    'authentication_id' => $request->authid,
			    'amount' => 1013,
			    'card_cvn' => '123',
			     'capture' => false
			];
$createCharge = \Xendit\Cards::create($params);

**Comment by stanleynguyen** [comment]
@msquareM the amount for credit charges should be at least 5000

**Comment by msquareM** [comment]
@stanleynguyen  thankyou so much now its working

**Comment by stanleynguyen** [comment]
@msquareM the pleasure's all mine
