### ISSUE TITLE
Amount is mismatch

### ISSUE THREAD

**Issue by msquareM** [xendit/xendit-php#85]
Hi ,
 this is mani when i pay through xendit (amount is 5000) after successful payment then go to gateway dashboard show  like below
**https://prnt.sc/su55t5 ,   https://prnt.sc/su55t5**  (payment amount is mismatch)

and  my code look like below
$params = [ 	 		'amount' => 5003,
					    'token_id' => $request->xendit_token,
					    'external_id' => 'card_'.time(),
					    'authentication_id' => $request->xendit_auth,			    
					    'card_cvn' => '123',
					    'capture' => true,
					    'currency'=>'IDR',
					];
$createCharge = \Xendit\Cards::create($params);

**Comment by stanleynguyen** [comment]
@msquareM Can't seem to find your request with amount 5003, would you mind trying again and give me the transaction's `external_id`?

**Comment by msquareM** [comment]
@stanleynguyen ok  now my amount is 5063 and my external_id is "card_1591337973"

**Comment by stanleynguyen** [comment]
@msquareM Can you show me how the amount mismatch?

**Comment by msquareM** [comment]
https://prnt.sc/su88zh

**Comment by stanleynguyen** [comment]
It's the correct amount 5063. We are using `.` as decimal separator
