### ISSUE TITLE
Get Blank Response

### ISSUE THREAD

**Issue by kotekaweb** [xendit/xendit-php#88]
i try to call balance api according this docs [https://xendit.github.io/apireference/?php#get-balance](url). But i dont get any response just blank page. please help

**Comment by stanleynguyen** [comment]
Can I see your code snippet? Also would you mind elaborating on `just blank page`?

**Comment by kotekaweb** [comment]
i did exactly like on docs :

<?php
  require 'vendor/autoload.php';

  $options['secret_api_key'] = 'xnd_development_P4qDfOss0OCpl8RtKrROHjaQYNCk9dN5lSfk+R1l9Wbe+rSiCwZ3jw==';

  $xenditPHPClient = new XenditClient\XenditPHPClient($options);

  $response = $xenditPHPClient->getBalance();
  print_r($response);
?>

i installed xendid-php with composer. but after that i dont get any response. Did i do anything wrong ?

**Comment by stanleynguyen** [comment]
It probably threw an error. Can you try wrapping this block in a try/catch and print out the error?

**Comment by stanleynguyen** [comment]
Stale
