### ISSUE TITLE
Payment not found

### ISSUE THREAD

**Issue by cierish** [xendit/xendit-php#93]
Hello Xendit team,

I tried to run the EwalletsExample.php and got error messages:
Fatal error: Uncaught Xendit\Exceptions\ApiException: Payment not found in /Users/kemkem/Downloads/xendit-php-master/src/HttpClient/GuzzleClient.php:167
Stack trace:
#0 /Users/kemkem/Downloads/xendit-php-master/src/HttpClient/GuzzleClient.php(140): Xendit\HttpClient\GuzzleClient::_handleAPIError(Array)
#1 /Users/kemkem/Downloads/xendit-php-master/src/HttpClient/GuzzleClient.php(90): Xendit\HttpClient\GuzzleClient->_executeRequest(Array, '/ewallets?exter...')
#2 /Users/kemkem/Downloads/xendit-php-master/src/ApiRequestor.php(87): Xendit\HttpClient\GuzzleClient->sendRequest('GET', '/ewallets?exter...', Array, Array)
#3 /Users/kemkem/Downloads/xendit-php-master/src/ApiRequestor.php(43): Xendit\ApiRequestor->_requestRaw('GET', '/ewallets?exter...', Array, Array)

What could be the cause? 
It seems the request has been sent.

Many thanks.

Cheers,
Cherry

**Comment by stanleynguyen** [comment]
HI @cierish you are probably passing in an incorrect external id of your payment

**Comment by cierish** [comment]
Hi @stanleynguyen,

Thank you for your quick reply. 

Is 'demo_' in original file not allowed? It works after I changed it into 'demo-' and define the callback URL in dashboard.

Many thanks!

**Comment by stanleynguyen** [comment]
> Hi @stanleynguyen,
> 
> Thank you for your quick reply.
> 
> Is 'demo_' in original file not allowed? It works after I changed it into 'demo-' and define the callback URL in dashboard.
> 
> Many thanks!

Hi @cierish , both should be fine, but there might have been an issue with url encoding 🤔 , can you pass me your external id values so I can try to reproduce the big?

**Comment by cierish** [comment]
Hi @stanleynguyen,

Sorry for late reply. I used the demo files:
'external_id' => 'demo_' . time(),
doesn't work.

Please tell me if you need more information.

Many thanks

**Comment by stanleynguyen** [comment]
Oh right, for ewallet, the only special charater that you can use is `-` according to https://xendit.github.io/apireference/#create-payment
@cierish
