### ISSUE TITLE
Pengalihan atau Checkout URL Pembayaran menggunakan OVO

### ISSUE THREAD

**Issue by cierish** [xendit/xendit-php#95]
Halo,

Saya ingin mengintegrasikan pembayaran xendit-php di dalam aplikasi, menggunakan eWallets.
Untuk pembayaran menggunakan OVO, bagaimanakah saya harus mengolah respon yang diberikan, atau mengalihkan pembayaran ke aplikasi OVO?

Saya belum jelas apakah pembayaran melalui OVO akan dialihkan ke webview atau membuka aplikasi OVO langsung. 

Di dalam dokumentasi tidak ada checkout url untuk ovo, dan saya belum menemukan penjelasan lebih lanjut untuk mengolah business id yang didapatkan sebagai respon pembayaran.

Terima kasih banyak sebelumnya.

Salam,
Cherry

**Comment by slzhffktm** [comment]
Halo Cherry,

Terima kasih atas ketertarikan Anda menggunakan Xendit

Anda tidak perlu melakukan handling tambahan untuk meneruskan response ke aplikasi OVO. Request payment akan langsung diteruskan ke aplikasi OVO melalui push notifikasi. Untuk melakukan pembayaran, end user perlu membuka aplikasi OVO untuk melakukan pembayaran. Supaya Anda memiliki gambaran mengenai payment flow OVO, Anda dapat mengakses dokumentasi kami berikut https://docs.xendit.co/id/xenpayments/e-wallet/alur-pembayaran-ewallet/index.html.  

Untuk OVO dikarenakan menggunakan push notifikasi ke aplikasi sehingga pada response tidak terdapat checkout_url.  

Untuk pertanyaan Anda mengenai business id. Business id adalah pengidentifikasi unik yang dibuat oleh system Xendit untuk setiap akun yang terdaftar di Xendit. Anda tidak perlu melakukan apapun untuk mengelola business id. Parameter ini akan dibuat secara otomatis oleh sistem Xendit sebagai penanda pembayaran tersebut dilakukan untuk akun Anda.

Salam,
Xendit

**Comment by cierish** [comment]
Halo @slzhffktm, 

Terima kasih banyak informasinya. Mohon maaf jika masih ada dokumentasi yang terlewatkan.
Kami akan mempelajari lebih lanjut dan mencoba mengimplementasikan.
Mohon dibantu, jika ada kendala dalam implementasi. 

Terima kasih.

Salam,
Cherry
