### ISSUE TITLE
Error code 400

### ISSUE THREAD

**Issue by cierish** [xendit/xendit-php#99]
Hi there, 

is there currently any problem with DANA server?

We got this error message while testing the API:
{"code":400,"error_message":"There was an external error from DANA. Please try again in a few minutes","error_code":"CHECKOUT_ERROR"}

I tried the example code, there was also same error:

Fatal error: Uncaught Xendit\Exceptions\ApiException: There was an external error from DANA. Please try again in a few minutes in /Users/xxx/Downloads/xendit-php-master/src/HttpClient/GuzzleClient.php:167
Stack trace:
#0 /Users/xxx/Downloads/xendit-php-master/src/HttpClient/GuzzleClient.php(140): Xendit\HttpClient\GuzzleClient::_handleAPIError(Array)
#1 /Users/xxx/Downloads/xendit-php-master/src/HttpClient/GuzzleClient.php(90): Xendit\HttpClient\GuzzleClient->_executeRequest(Array, '/ewallets')
#2 /Users/xxx/Downloads/xendit-php-master/src/ApiRequestor.php(87): Xendit\HttpClient\GuzzleClient->sendRequest('POST', '/ewallets', Array, Array)
#3 /Users/xxx/Downloads/xendit-php-master/src/ApiRequestor.php(43): Xendit\ApiRequestor->_requestRaw('POST', '/ewallets', Array, Array)
#4 /Users/xxx/Downloads/xendit-php-master/src/ApiOperations/Request.php(76): Xendit\ApiRequestor->request('POST', '/ewallets', Array, Array)
#5 /Users/xxx/Downloads/xendit-php-master/src/EWallets.php(73): Xendit\EWallets::_request('P in /Users/xxx/Downloads/xendit-php-master/src/HttpClient/GuzzleClient.php on line 167

Many thanks before.

Cheers,
Cherry

**Comment by stanleynguyen** [comment]
This is an error from our partner DANA. Please try again after a while
